# Generated by Django 4.1.5 on 2025-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterModelOptions(
            name='diascredito',
            options={'ordering': ['dias']},
        ),
        migrations.AlterModelOptions(
            name='tipoformapago',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='tipoventa',
            options={'ordering': ['descripcion']},
        ),
    ]
