# Generated by Django 4.1.5 on 2025-10-09 16:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0002_estadoubicacion_alter_diascredito_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=250, null=True)),
                ('dirección', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 9 dígitos', regex='^\\+?\\d{9}$')])),
                ('contacto', models.CharField(blank=True, max_length=250, null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario asociado a este cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
