# Generated by Django 4.1.5 on 2025-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(blank=True, help_text='Ingrese un correo electrónico válido.', max_length=254, null=True),
        ),
    ]
