# Generated by Django 4.1.5 on 2025-10-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_clientes_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
