# Generated by Django 4.1.5 on 2025-10-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_rename_dirección_clientes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
