# Generated by Django 4.1.5 on 2025-10-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0007_estadofijasdigital_remove_ubicacion_estado'),
        ('parametros', '0007_alter_clientes_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoUbicacion',
        ),
    ]
