# Generated by Django 4.1.5 on 2025-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_delete_estadoubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo_contacto',
            field=models.EmailField(blank=True, help_text='Ingrese un correo electrónico válido.', max_length=254, null=True),
        ),
    ]
