# Generated by Django 4.1.5 on 2025-10-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapedido',
            name='numero_np',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
