# Generated by Django 4.1.5 on 2025-10-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_notapedido_numero_np'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notapedido',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='notapedido',
            name='fecha_creacion',
        ),
    ]
