# Generated by Django 4.1.5 on 2025-10-16 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_alter_clientes_ruc'),
        ('pedidos', '0004_detalleubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notapedido',
            name='dias_credito',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametros.diascredito'),
        ),
    ]
