# Generated by Django 4.1.5 on 2025-10-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_notapedido_dias_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroNotaProgramatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='guias/')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_programatica', to='pedidos.notapedido')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroNotaDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='guias/')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_directo', to='pedidos.notapedido')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroNotaCanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='guias/')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_canje', to='pedidos.notapedido')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroNotaBonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='guias/')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_bonificacion', to='pedidos.notapedido')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroNotaAgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='guias/')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_agencia', to='pedidos.notapedido')),
            ],
        ),
    ]
