# Generated by Django 4.1.5 on 2025-10-17 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0007_numeronotaprogramatica_numeronotadirecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapedido',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario asociado a este cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
