# Generated by Django 4.1.5 on 2025-10-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_estadonota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadonota',
            options={'ordering': ['descripcion']},
        ),
        migrations.AddField(
            model_name='notapedido',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.estadonota'),
        ),
    ]
