# Generated by Django 4.1.5 on 2025-10-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0008_alter_reservaslot_estado'),
        ('pedidos', '0010_alter_estadonota_options_notapedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleubicacion',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estado_ubi_fija', to='ubicaciones.estadofijasdigital'),
        ),
    ]
