# Generated by Django 4.1.5 on 2025-10-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0009_ubicacion_tarifa_fria'),
        ('pedidos', '0011_detalleubicacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleubicacion',
            name='estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='estado_ubi_fija', to='ubicaciones.estadofijasdigital'),
        ),
        migrations.AlterField(
            model_name='notapedido',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.estadonota'),
        ),
    ]
