# Generated by Django 4.1.5 on 2025-11-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_detalleubicacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleubicacion',
            name='tarifa_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleubicacion',
            name='tarifa_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleubicacion',
            name='total_tarifa_ubi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
