# Generated by Django 4.1.5 on 2025-11-06 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_detalleubicacion_tarifa_dia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notapedido',
            old_name='tarifa',
            new_name='tarifa_digital',
        ),
        migrations.RenameField(
            model_name='notapedido',
            old_name='tarifa_neg',
            new_name='tarifa_estatica',
        ),
    ]
