# Generated by Django 4.1.5 on 2025-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_rename_tarifa_notapedido_tarifa_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapedido',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
