# Generated by Django 4.1.5 on 2025-11-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_notapedido_motivo_anulacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notapedido',
            old_name='motivo_anulacion',
            new_name='motivo_rechazo_anulacion',
        ),
    ]
