# Generated by Django 4.1.5 on 2025-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_rename_motivo_anulacion_notapedido_motivo_rechazo_anulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField()),
                ('primer_login', models.BooleanField(default=False)),
            ],
        ),
    ]
