# Generated by Django 4.1.5 on 2025-11-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_controlusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapedido',
            name='rel_edicion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
