# Generated by Django 4.1.5 on 2025-10-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0002_estadoubicacion_alter_diascredito_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('referencia', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.estadoubicacion')),
            ],
        ),
    ]
