# Generated by Django 4.1.5 on 2025-10-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_detalleubicacion'),
        ('ubicaciones', '0002_tipoubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicaciones.tipoubicacion'),
        ),
        migrations.CreateModel(
            name='SlotDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_slot', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ubicaciones.ubicacion')),
            ],
            options={
                'unique_together': {('ubicacion', 'numero_slot')},
            },
        ),
        migrations.CreateModel(
            name='ReservaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('LIBRE', 'Libre'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20)),
                ('nota_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_nota', to='pedidos.notapedido')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ubicaciones.slotdigital')),
            ],
        ),
        migrations.AddIndex(
            model_name='reservaslot',
            index=models.Index(fields=['slot', 'fecha_inicio', 'fecha_fin'], name='ubicaciones_slot_id_15461f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservaslot',
            unique_together={('slot', 'fecha_inicio', 'fecha_fin')},
        ),
    ]
