# Generated by Django 4.1.5 on 2025-10-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0003_ubicacion_tipo_slotdigital_reservaslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdigital',
            name='nombre',
        ),
    ]
