# Generated by Django 4.1.5 on 2025-10-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0004_remove_slotdigital_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdigital',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
