# Generated by Django 4.1.5 on 2025-10-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0005_slotdigital_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaslot',
            name='dias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
