# Generated by Django 4.1.5 on 2025-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0006_reservaslot_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFijasDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='estado',
        ),
    ]
