# Generated by Django 4.1.5 on 2025-10-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0007_estadofijasdigital_remove_ubicacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaslot',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_ubi_slot', to='ubicaciones.estadofijasdigital'),
        ),
    ]
