# Generated by Django 4.1.5 on 2025-10-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0008_alter_reservaslot_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='tarifa_fria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
