# Generated by Django 4.1.5 on 2025-10-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0009_ubicacion_tarifa_fria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='medidas',
            field=models.CharField(blank=True, default='No especificado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='medidas_pixel',
            field=models.CharField(blank=True, default='No especificado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='pixel_pitch',
            field=models.CharField(blank=True, default='No especificado', max_length=100, null=True),
        ),
    ]
