# Generated by Django 4.1.5 on 2025-10-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0010_ubicacion_medidas_ubicacion_medidas_pixel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdigital',
            name='es_canje',
            field=models.BooleanField(default=False),
        ),
    ]
