# Generated by Django 4.1.5 on 2025-10-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0011_slotdigital_es_canje'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservaslot',
            unique_together=set(),
        ),
    ]
