# Generated by Django 4.1.5 on 2025-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0012_alter_reservaslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdigital',
            name='tarifa_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='slotdigital',
            name='tarifa_fria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='slotdigital',
            name='tarifa_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='slotdigital',
            name='total_tarifa_slot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
