# Generated by Django 4.1.5 on 2025-11-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0013_slotdigital_tarifa_dia_slotdigital_tarifa_fria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdigital',
            name='tarifa_dia',
        ),
        migrations.RemoveField(
            model_name='slotdigital',
            name='tarifa_mes',
        ),
        migrations.RemoveField(
            model_name='slotdigital',
            name='total_tarifa_slot',
        ),
        migrations.AddField(
            model_name='reservaslot',
            name='tarifa_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservaslot',
            name='tarifa_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservaslot',
            name='total_tarifa_slot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
