# Generated by Django 4.1.5 on 2025-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0014_remove_slotdigital_tarifa_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='tarifa_minima',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
