# Generated by Django 4.1.5 on 2025-11-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0015_ubicacion_tarifa_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdigital',
            name='tarifa_minima',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
